### ISSUE TITLE
Support Armor in addition to Shields

### ISSUE THREAD

**Issue by sfiera** [arescentral/antares#366]
Ares supports a single health metric, shielding. Escape Velocity has two: shields and armor.

Proposal: add armor as a separate kind of health, allowing plugins to support EV-like armor/shields.

Object data files need the corresponding information:
```
health:
  shields: 1000
  armor: 500
collide:
  damage:
    shields: 1
    armor: 50
```
Code that deals with health (collisions, heal action, recharge) needs to respect these numbers as well.

Also, the shield bar drawing code needs to draw an armor bar, if the shields are at zero.
